### PR TITLE
Update code base to use HTTPs

### PR DESCRIPTION
**Pull request by KrauseFx**
MyFitnessPal doesn't have an official API, but attackers can just access the data, so that's nice.

Either way, it seems like they now enforce HTTPs, which is a good thing, so let's update the code base of mfp to use HTTPs also 👍

The previous version without the use of HTTPs didn't work for me

### CODE REVIEW

**Comment by KrauseFx** [comment]
I'm using this fork successfully for https://github.com/krausefx/whereisfelix.today 👍

**Comment by Aubron** [comment]
@KrauseFx - Did a test update to this on my projects, and all seems to be good. Will be pushing this out immediately as a Minor level update. It could still screw with systems with fringe HTTPS issues, but that almost certainly won't come up.

Thanks for your contribution! Keep an eye here, we're still wanting to do a 1.0 rewrite of the project in the next month or two, if you feel like contributing 👍 

(whoops, hit close and comment)

**Comment by KrauseFx** [comment]
Hey @andrewzey and @Aubron, sounds good, I'm a Ruby dev (creator of [fastlane](https://github.com/fastlane/fastlane) working exclusively on open source software, as part of this I created [spaceship](https://spaceship.airforce), so I did a ton of reverse engineering and investigating network traffic.

I feel like I can help out when it comes to those things, however I'm brand new to JavaScript/Node, etc, I just picked it up to create https://whereisfelix.today. 

Summary: I'd love to help out, and will probably need some guidance, and some reviews on the code I write 👍 Happy to help & learn

**Comment by andrewzey** [comment]
Hey @KrauseFx, that sounds fantastic! I'm pretty tied up for the next couple months, but if Aubron proceeds with the 1.0 rewrite, I'd sure be glad to have you on board. After that, I'd love to do some planning sessions together to see what we can do together.

**Comment by KrauseFx** [comment]
Cool, keep me posted 👍 Due to how GitHub notifications work, and the amount of fastlane notifications I get, feel free to also ping me on Twitter/Email in case I don't respond on GitHub right away

**Pull request merged**
